### ISSUE TITLE
[Feature Request] Can you add image resolution to package?

### ISSUE THREAD

**Issue by Joe2316** [VisionCraft-org/flutter_vision_craft#1]
Hi bro

Can you add a different image resolution please, I tried the  API, and it gives me "detail": "Method Not Allowed". Thanks :)

**Comment by KarlMathuthu** [comment]
Hi @Joe2316 , I really appreciate that you like our package. I hear your request, I'm currently waiting a response from @Metim0l who is the backend developer of the package. I'll receive a message from him soon, As soon as i do, I'll release a new version of the package. Please don't forget to star our project. 

If you like it, Please consider donating so that we will be able to pay for the servers, Thanks 🙏.

PayPal : karlmathuthu07@gmail.com
KO-FI : https://ko-fi.com/karlmathuthu

**Comment by KarlMathuthu** [comment]
Hi there @Joe2316 , I have added the XLModels which support custom Image resolutions, Please checkout the new version.

**Comment by KarlMathuthu** [comment]
Enjoy 🔥🚀
